
4. Write a Python Program to Sort Words in Alphabetic Order?


In [1]:
import numpy as np

In [11]:
#  let us create 2 matrices
mat1=np.random.randint(1,10,size=(3,3))
mat2=np.random.randint(23,55,size=(3,3))

In [12]:
mat1

array([[8, 1, 2],
       [9, 2, 9],
       [2, 8, 9]])

In [13]:
 mat2

array([[45, 42, 42],
       [48, 44, 47],
       [54, 54, 35]])

1. Write a Python Program to Add Two Matrices?

In [16]:
np.add(mat1, mat2)

array([[53, 43, 44],
       [57, 46, 56],
       [56, 62, 44]])

2. Write a Python Program to Multiply Two Matrices?

In [15]:
np.multiply(mat1,mat2)

array([[360,  42,  84],
       [432,  88, 423],
       [108, 432, 315]])

3. Write a Python Program to Transpose a Matrix?

In [14]:
np.transpose(mat1)

array([[8, 9, 2],
       [1, 2, 8],
       [2, 9, 9]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [30]:
num=int(input('how many words you want to enter: '))
l=[]
for n in range(num):
    st=str(input(f'word{n}: '))
    l.append(st)
    
print(f"sorted words are {sorted(l)}")




how many words you want to enter: 5
word0: eadks
word1: rwjksfnmvc
word2: oyfhklg
word3: awejhdsn
word4: xd
sorted words are ['awejhdsn', 'eadks', 'oyfhklg', 'rwjksfnmvc', 'xd']


5. Write a Python Program to Remove Punctuation From a String?


In [43]:
import pandas as pd
text=input("please input a string: ")
punctuation="!@#$%^&*()/"
for char in punctuation:

    if char in text:
        text=text.replace(char, '')
print(text)


please input a string: sgf!@#$
sgf
